### PR TITLE
Updates for rebar 3.18

### PR DESCRIPTION
**Pull request by lukebakken**

### CODE REVIEW

**Review by deadtrickster — APPROVED** [review]

**Comment by dumbbell** [comment]
Just to make sure, how did you proceed with the update? Did you copy the original source files from Rebar 3.18.0?

**Comment by lukebakken** [comment]
> Did you copy the original source files from Rebar 3.18.0?

Yep, I diffed between the files in this repo vs what was downloaded into `deps/rebar`.

**Review by dumbbell — APPROVED** [review]

**Comment by dumbbell** [comment]
Cool! Thank you :-)

**Comment by lukebakken** [comment]
Thanks everyone. I'll get a new release out today.

**Comment by lukebakken** [comment]
https://github.com/rabbitmq/hexpm-cli/releases/tag/v0.9.0

**Pull request merged**
